spring:
  datasource:
    url: jdbc:mysql://192.168.208.102:13306/mybatis?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml



